# Generated by Django 3.2.9 on 2021-12-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='big_image',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='small_image',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
