# Generated by Django 3.2.9 on 2021-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211202_2201'),
        ('cart', '0004_alter_cart_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_items',
            field=models.ManyToManyField(blank=True, related_name='cartItem', to='products.Product'),
        ),
    ]
